all:
	arm-elf-gcc -g aufgabe1.S -o aufgabe1.elf
	arm-elf-gcc -g aufgabe1mL.S -o aufgabe1mL.elf
	arm-elf-gcc -g aufgabe2.S -o aufgabe2.elf	
	arm-elf-gcc -g aufgabe2mL.S -o aufgabe2mL.elf	
	arm-elf-gcc -g aufgabe3.S -o aufgabe3.elf
	arm-elf-gcc -g aufgabe4.S -o aufgabe4.elf
	arm-elf-gcc -g aufgabe4mL.S -o aufgabe4mL.elf

